function main()
    % main.m
    % Skrypt główny do uruchamiania funkcji z przyciskami i tekstem

    clc;
    clear;
    close all;

    % Kolory pastelowe w formacie RGB
    pastel_light_green = [204, 255, 204] / 255; % Jasnozielony pastelowy
    pastel_dark_green = [153, 204, 153] / 255; % Ciemnozielony pastelowy
    pastel_red = [255, 204, 204] / 255;        % Pastelowy czerwony

    % Tworzenie głównego okna aplikacji
    fig = uifigure('Name', 'Menu główne', 'Position', [500 300 400 600]);
    movegui(fig, 'center'); % Wyśrodkowanie okna na ekranie

    % Dodanie tekstu na górze
    uilabel(fig, ...
        'Text', 'Menu - Robot OPP', ...
        'Position', [50 550 300 40], ... % Pozycja i rozmiar tekstu
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center');

    % Przyciski górne (jasnozielone pastelowe)
    uibutton(fig, 'Text', 'Wyświetl przestrzeń roboczą', ...
        'Position', [100 450 200 40], ...
        'BackgroundColor', pastel_light_green, ...
        'ButtonPushedFcn', @(~,~) przestrzen_robocza());

    uibutton(fig, 'Text', 'Kinematyka prosta', ...
        'Position', [100 390 200 40], ...
        'BackgroundColor', pastel_light_green, ...
        'ButtonPushedFcn', @(~,~) kinematykaProsta());

    uibutton(fig, 'Text', 'Kinematyka odwrotna', ...
        'Position', [100 330 200 40], ...
        'BackgroundColor', pastel_light_green, ...
        'ButtonPushedFcn', @(~,~) disp('Jeszcze nie gotowe'));

    % Przyciski dolne (ciemnozielone pastelowe)
    uibutton(fig, 'Text', 'Analiza wstępna silników', ...
        'Position', [100 250 200 40], ...
        'BackgroundColor', pastel_dark_green, ...
        'ButtonPushedFcn', @(~,~) submenuAnalizaWstepna());

    uibutton(fig, 'Text', 'Maksymalna prędkość końcówki', ...
        'Position', [100 190 200 40], ...
        'BackgroundColor', pastel_dark_green, ...
        'ButtonPushedFcn', @(~,~) maxPredkoscKinProsta());

    % Przycisk wyjścia (pastelowy czerwony)
    uibutton(fig, 'Text', 'Zakończ program', ...
        'Position', [100 110 200 40], ...
        'BackgroundColor', pastel_red, ...
        'ButtonPushedFcn', @(~,~) close(fig));

    % Dodanie tekstu na dole
    uilabel(fig, ...
        'Text', 'Konrad Szolc, Marceli Ryżewski - Politechnika Opolska 2024', ...
        'Position', [50 20 300 20], ... % Pozycja i rozmiar tekstu
        'FontSize', 11, ...
        'HorizontalAlignment', 'center', ...
        'FontAngle', 'italic', ...
        'FontColor', [0.5 0.5 0.5]); % Szary kolor tekstu
end

function submenuAnalizaWstepna()
    % submenuAnalizaWstepna - Submenu dla analizy wstępnej silników
    pastel_light_green = [204, 255, 204] / 255; % Jasnozielony pastelowy

    fig_submenu = uifigure('Name', 'Analiza Wstępna Silników', 'Position', [600 350 300 400]);
    movegui(fig_submenu, 'center'); % Wyśrodkowanie okna na ekranie

    % Dodanie tekstu na górze
    uilabel(fig_submenu, ...
        'Text', 'Analiza Wstępna Silników', ...
        'Position', [50 350 200 40], ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center');

    % Przyciski dla analizy Q1, Q2, Q3
    uibutton(fig_submenu, 'Text', 'Analiza Q1', ...
        'Position', [50 280 200 40], ...
        'BackgroundColor', pastel_light_green, ...
        'ButtonPushedFcn', @(~,~) Q1_analiza_wstepna());

    uibutton(fig_submenu, 'Text', 'Analiza Q2', ...
        'Position', [50 220 200 40], ...
        'BackgroundColor', pastel_light_green, ...
        'ButtonPushedFcn', @(~,~) Q2_analiza_wstepna());

    uibutton(fig_submenu, 'Text', 'Analiza Q3', ...
        'Position', [50 160 200 40], ...
        'BackgroundColor', pastel_light_green, ...
        'ButtonPushedFcn', @(~,~) Q3_analiza_wstepna());

    % Przycisk zamknięcia submenu
    uibutton(fig_submenu, 'Text', 'Zamknij', ...
        'Position', [50 100 200 40], ...
        'BackgroundColor', [255, 204, 204] / 255, ... % Pastelowy czerwony
        'ButtonPushedFcn', @(~,~) close(fig_submenu));
end
